# Generated by Django 4.2.3 on 2023-11-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
